/*
 * TaskSummaryPanel.java
 *
 * Created on Nov 26, 2011, 9:16:15 AM
 */
package taskdirector.ui.panels;

import java.util.List;
import taskdirector.services.viewmodels.TaskSummaryViewModel;

/**
 *
 * @author KallDrexx
 */
public class TaskSummaryPanel extends javax.swing.JPanel {

    /** Creates new form TaskSummaryPanel */
    public TaskSummaryPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        completionProgress = new javax.swing.JProgressBar();
        openTaskCountLabel = new javax.swing.JLabel();
        closedTaskCountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Open Tasks:");

        jLabel2.setText("Closed Tasks:");

        completionProgress.setToolTipText("Task Completion ");
        completionProgress.setStringPainted(true);

        openTaskCountLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        openTaskCountLabel.setText("0");

        closedTaskCountLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        closedTaskCountLabel.setText("0");

        jLabel3.setText("Task Completion Progress:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(completionProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closedTaskCountLabel)
                            .addComponent(openTaskCountLabel))))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openTaskCountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closedTaskCountLabel)))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completionProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closedTaskCountLabel;
    private javax.swing.JProgressBar completionProgress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel openTaskCountLabel;
    // End of variables declaration//GEN-END:variables

    public void UpdateSummary(List<TaskSummaryViewModel> tasks)
    {
        if (tasks == null)
            return;
        
        int openCount = 0;
        int completedCount = 0;
        int totalCount = 0;
        
        for (TaskSummaryViewModel task : tasks)
        {
            if (task.getIsCompleted())
                completedCount++;
            else
                openCount++;
        }
        
        totalCount = tasks.size();
        
        // Update the labels
        openTaskCountLabel.setText(Integer.toString(openCount));
        closedTaskCountLabel.setText(Integer.toString(completedCount));
        
        // Update the progress bar
        completionProgress.setMaximum(totalCount);
        completionProgress.setValue(completedCount);
    }
}
